[package]
name = "mkt-import"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mkt-data = { path = "../mkt-data" }
image = "0.23.14"
imageproc = "0.22.0"
itertools = "0.10.1"
img_hash = "3.2.0"