[package]
name = "mkt-inventory-web"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mkt-data = { path = "../mkt-data" }
mkt-import = { path = "../mkt-import" }
yew = "0.18"
