name: web deploy

on:
  push:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        target: wasm32-unknown-unknown
        override: true
        profile: minimal
        
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          cargo-${{ runner.os }}-

    - uses: jetli/trunk-action@v0.1.0
      with:
        # Optional version of trunk to install(eg. 'v0.8.1', 'latest')
        version: 'latest'

    - uses: jetli/wasm-bindgen-action@v0.1.0
      with:
        # Optional version of wasm-bindgen to install(eg. '0.2.68', 'latest')
        version: 'latest'
        
    - name: Build
      run: trunk build --release
      working-directory: ./mkt-inventory-web
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./mkt-inventory-web/dist # The folder the action should deploy.
        clean-exclude: 'mkt_*.json'
